In [1]:
%pip install numpy



In [2]:
import numpy as np

In [4]:
lst=list(range(1,25))#different data type,less speed
arr=np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [8]:
#creating numpy array
                                            #lst=list(range(5))
                                 #print(lst)
#                                       print(arr)

In [13]:
arr=np.arange(1,25)  #arrange():used to create the array
arr           #single dimension array                          
     

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
#2d array
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
#2d array
arr=np.array([[1,2,3],[4,5,6],[5,6,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 8]])

In [20]:
#3d array
arr=np.array([[[1,2,3,4],[4,5,6,7],[1,2,3,4]],[[9,10,11,12],[13,23,44,56],[1,3,4,5]]])
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12],
        [13, 23, 44, 56],
        [ 1,  3,  4,  5]]])

In [6]:
import numpy as np
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr= np.linspace(3,545,6)    #linspace for the 6 values between 3 and 545
arr

array([  3. , 111.4, 219.8, 328.2, 436.6, 545. ])

In [ ]:
arr=np.linspace(1,10,5).reshape(5,1)   # reshape is used for row(5) or column(1) and linspace take 5 value between1 and 10
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [ ]:
#1d to 2d convergence
arr=np.arange(0,30).reshape(3,10)  #take reshape value as the value wich is multiple of 30(element in arrange)
arr
#arr.shape for finding te shape of element

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
arr.reshape(3,5,2)  #3 bracket, 5 row,2 column


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [ ]:
arr=np.random.random(10)         #generate 10 random value
arr

array([0.13646065, 0.29924954, 0.31912017, 0.85498231, 0.19885026,
       0.43777778, 0.81203508, 0.01825748, 0.23210263, 0.67508457])

In [ ]:
arr=np.random.random((5,2))         #generate 10 random value and generate 2d array
arr

array([[0.92774567, 0.7493044 ],
       [0.85942124, 0.20135857],
       [0.25452902, 0.36987502],
       [0.13352212, 0.24052613],
       [0.50863919, 0.73009503]])

In [ ]:
arr=np.random.randint(1,5,9)  # generate 9 random number between 1 and 5
arr

array([4, 4, 2, 1, 1, 1, 2, 2, 3])

In [ ]:
arr.dtype    #check data type

dtype('float64')

In [ ]:
arr=np.random.randint(1,5,(3,3)) # generate 9 random number between 1 and 5  and 2d array
arr

array([[4, 4, 4],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
arr=np.random.randint(1,5,(3,4,4))  #  and 3d array
arr

array([[[4, 3, 2, 1],
        [2, 2, 1, 4],
        [1, 4, 1, 3],
        [3, 2, 1, 4]],

       [[1, 4, 2, 4],
        [3, 4, 3, 3],
        [4, 3, 4, 3],
        [1, 3, 3, 2]],

       [[3, 4, 4, 4],
        [1, 3, 2, 2],
        [3, 4, 3, 2],
        [1, 3, 4, 1]]])

In [ ]:
arr=np.random.random(10)    #generate 10 random value between 0 and 1
arr

array([0.48914303, 0.10160096, 0.68852586, 0.09837614, 0.4058812 ,
       0.84875707, 0.38411794, 0.56912463, 0.80177096, 0.50569062])

In [ ]:
arr=np.random.randint(10)  #by default print 1 value between 1 to 10
arr

3

In [ ]:
arr=np.random.random((5,2))  # generate 2d by random 
arr

array([[0.99971037, 0.28957484],
       [0.30992716, 0.06947502],
       [0.78920771, 0.94573015],
       [0.20318299, 0.75607412],
       [0.63333217, 0.1447715 ]])

In [ ]:
arr=np.arange(60).reshape(10,6)    #arr.dtype is used to check data type
print(arr)
arr.dtype


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [ ]:
arr=np.arange(60).reshape(10,6)    #arr.dtype is used to check data type
print(arr)
print(arr.dtype)
print(arr.ndim)   #dimension
print(arr.size )         # element total(size)
arr.shape                #row and column

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
int32
2
60


(10, 6)

In [ ]:
#convert 2 or 3d in 1d 
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.ravel()   #convert in linear form in one d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [54]:
lst=[[1,2,3],[1,2,3]]
arr=np.array(lst)
arr.shape


(2, 3)

In [ ]:
arr.T.shape  #transpose shape

(3, 2)

In [ ]:
arr.T   #generate transpose array

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
arr.ndim #dimension

2

In [5]:
import numpy as np
lst=[1,2,3,4,5,1]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 1])

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
lst=list(range(0,20))  #to create list using arange function
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
arr=np.ones((4,5))  #to genetrate 2d array
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
list_2d=[[1,2,3],[3,4,5]]      #convert 2d list into array
list_2d
arr=np.array(list_2d)
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [29]:
arr.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [33]:
#slicing and indexing
#index(0)and position(1)
arr=np.random.random(10)
arr

array([0.74735656, 0.2678477 , 0.21070088, 0.35904496, 0.58428698,
       0.13592234, 0.38988751, 0.84022308, 0.7829497 , 0.9835601 ])

In [ ]:
arr[1]  #indexing

0.2678476998226106

In [ ]:
arr[2:9]    #slicing  start from 2 and end at 8

array([0.21070088, 0.35904496, 0.58428698, 0.13592234, 0.38988751,
       0.84022308, 0.7829497 ])

In [ ]:

arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr[0:20:2] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
arr=arr.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [42]:
arr[1]

array([5, 6, 7, 8, 9])

In [44]:
arr[0:5]    

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[0:5,1:2]   #1 column element access

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [ ]:
arr[11,4]# last element access

59

In [51]:
arr[11][-1]

59

In [52]:
arr[-1][-1]

59

In [49]:
arr[2,2]   #column 2 element 2 access

12

In [76]:
arr[:4][1]

array([5, 6, 7, 8, 9])

In [ ]:
arr[4,2]=100  #replace the 4 th row 3rd element by 100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [62]:
arr=np.arange(225)
arr=arr.reshape(5,15,3)
arr


array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [77]:
arr+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61]])

In [58]:
arr.shape

(225,)

In [63]:
arr[1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [64]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [65]:
arr=np.arange(60)

In [67]:
arr=arr.reshape(12,5)

In [69]:
arr[2,2]

12

In [70]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr[2,3]  #2 row and 3 column element 13 is printed

13

In [78]:
arr=arr.reshape(12,5)

In [79]:
arr1=np.arange(60)

In [80]:
arr1=arr1.reshape(12,5)

In [82]:
arr+arr1

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [99]:
listx=[1,2,3,4]
listy=[4.5,5,6,7]
listx+listy


[1, 2, 3, 4, 4.5, 5, 6, 7]

In [100]:
arr1=np.array(listx)
arr2=np.array(listy)
arr=arr1+arr2
arr

array([ 5.5,  7. ,  9. , 11. ])

In [98]:
arr=arr1*arr2
arr

array([ 4, 10, 18, 28])